services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.11
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: wb
      CLICKHOUSE_USER: app
      CLICKHOUSE_PASSWORD: app_pass
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user=app --password=app_pass --query='SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: ./app
    restart: "no"
    depends_on:
      clickhouse:
        condition: service_healthy